#!/bin/bash

make menuselect.makeopts

menuselect/menuselect --enable chan_mobile menuselect.makeopts
menuselect/menuselect --enable format_mp3 menuselect.makeopts
menuselect/menuselect --enable res_config_mysql menuselect.makeopts

menuselect/menuselect --enable app_agent_pool menuselect.makeopts
menuselect/menuselect --enable app_authenticate menuselect.makeopts
menuselect/menuselect --enable app_bridgeaddchan menuselect.makeopts
menuselect/menuselect --enable app_bridgewait menuselect.makeopts
menuselect/menuselect --enable app_cdr menuselect.makeopts
menuselect/menuselect --enable app_celgenuserevent menuselect.makeopts
menuselect/menuselect --enable app_channelredirect menuselect.makeopts
menuselect/menuselect --enable app_chanspy menuselect.makeopts
menuselect/menuselect --enable app_confbridge menuselect.makeopts
menuselect/menuselect --enable app_controlplayback menuselect.makeopts
menuselect/menuselect --enable app_db menuselect.makeopts
menuselect/menuselect --enable app_dial menuselect.makeopts
menuselect/menuselect --enable app_directed_pickup menuselect.makeopts
menuselect/menuselect --enable app_directory menuselect.makeopts
menuselect/menuselect --enable app_disa menuselect.makeopts
menuselect/menuselect --enable app_dumpchan menuselect.makeopts
menuselect/menuselect --enable app_echo menuselect.makeopts
menuselect/menuselect --enable app_exec menuselect.makeopts
menuselect/menuselect --enable app_followme menuselect.makeopts
menuselect/menuselect --enable app_forkcdr menuselect.makeopts
menuselect/menuselect --enable app_milliwatt menuselect.makeopts
menuselect/menuselect --enable app_mixmonitor menuselect.makeopts
menuselect/menuselect --enable app_originate menuselect.makeopts
menuselect/menuselect --enable app_page menuselect.makeopts
menuselect/menuselect --enable app_playback menuselect.makeopts
menuselect/menuselect --enable app_playtones menuselect.makeopts
menuselect/menuselect --enable app_privacy menuselect.makeopts
menuselect/menuselect --enable app_queue menuselect.makeopts
menuselect/menuselect --enable app_read menuselect.makeopts
menuselect/menuselect --enable app_readexten menuselect.makeopts
menuselect/menuselect --enable app_record menuselect.makeopts
menuselect/menuselect --enable app_sayunixtime menuselect.makeopts
menuselect/menuselect --enable app_senddtmf menuselect.makeopts
menuselect/menuselect --enable app_sendtext menuselect.makeopts
menuselect/menuselect --enable app_softhangup menuselect.makeopts
menuselect/menuselect --enable app_speech_utils menuselect.makeopts
menuselect/menuselect --enable app_stack menuselect.makeopts
menuselect/menuselect --enable app_stasis menuselect.makeopts
menuselect/menuselect --enable app_stream_echo menuselect.makeopts
menuselect/menuselect --enable app_system menuselect.makeopts
menuselect/menuselect --enable app_talkdetect menuselect.makeopts
menuselect/menuselect --enable app_transfer menuselect.makeopts
menuselect/menuselect --enable app_userevent menuselect.makeopts
menuselect/menuselect --enable app_verbose menuselect.makeopts
menuselect/menuselect --enable app_voicemail menuselect.makeopts
menuselect/menuselect --enable app_voicemail_odbc menuselect.makeopts
menuselect/menuselect --enable app_waituntil menuselect.makeopts
menuselect/menuselect --enable app_while menuselect.makeopts
menuselect/menuselect --enable app_alarmreceiver menuselect.makeopts
menuselect/menuselect --enable app_amd menuselect.makeopts
menuselect/menuselect --enable app_attended_transfer menuselect.makeopts
menuselect/menuselect --enable app_audiosocket menuselect.makeopts
menuselect/menuselect --enable app_blind_transfer menuselect.makeopts
menuselect/menuselect --enable app_broadcast menuselect.makeopts
menuselect/menuselect --enable app_chanisavail menuselect.makeopts
menuselect/menuselect --enable app_dictate menuselect.makeopts
menuselect/menuselect --enable app_dtmfstore menuselect.makeopts
menuselect/menuselect --enable app_externalivr menuselect.makeopts
menuselect/menuselect --enable app_festival menuselect.makeopts
menuselect/menuselect --enable app_if menuselect.makeopts
menuselect/menuselect --enable app_jack menuselect.makeopts
menuselect/menuselect --enable app_meetme menuselect.makeopts
menuselect/menuselect --enable app_mf menuselect.makeopts
menuselect/menuselect --enable app_minivm menuselect.makeopts
menuselect/menuselect --enable app_morsecode menuselect.makeopts
menuselect/menuselect --enable app_mp3 menuselect.makeopts
menuselect/menuselect --enable app_reload menuselect.makeopts
menuselect/menuselect --enable app_sf menuselect.makeopts
menuselect/menuselect --enable app_signal menuselect.makeopts
menuselect/menuselect --enable app_sms menuselect.makeopts
menuselect/menuselect --enable app_test menuselect.makeopts
menuselect/menuselect --enable app_waitforcond menuselect.makeopts
menuselect/menuselect --enable app_waitforring menuselect.makeopts
menuselect/menuselect --enable app_waitforsilence menuselect.makeopts
menuselect/menuselect --enable app_zapateller menuselect.makeopts
menuselect/menuselect --enable app_adsiprog menuselect.makeopts
menuselect/menuselect --enable app_getcpeid menuselect.makeopts
menuselect/menuselect --enable app_ices menuselect.makeopts
menuselect/menuselect --enable app_image menuselect.makeopts
menuselect/menuselect --enable app_macro menuselect.makeopts
menuselect/menuselect --enable app_nbscat menuselect.makeopts
menuselect/menuselect --enable app_url menuselect.makeopts

menuselect/menuselect --enable bridge_builtin_features menuselect.makeopts
menuselect/menuselect --enable bridge_builtin_interval_features menuselect.makeopts
menuselect/menuselect --enable bridge_holding menuselect.makeopts
menuselect/menuselect --enable bridge_native_rtp menuselect.makeopts
menuselect/menuselect --enable bridge_simple menuselect.makeopts
menuselect/menuselect --enable bridge_softmix menuselect.makeopts

menuselect/menuselect --enable cdr_adaptive_odbc menuselect.makeopts
menuselect/menuselect --enable cdr_custom menuselect.makeopts
menuselect/menuselect --enable cdr_manager menuselect.makeopts
menuselect/menuselect --enable cdr_csv menuselect.makeopts
menuselect/menuselect --enable cdr_odbc menuselect.makeopts
menuselect/menuselect --enable cdr_pgsql menuselect.makeopts
menuselect/menuselect --enable cdr_radius menuselect.makeopts
menuselect/menuselect --enable cdr_sqlite3_custom menuselect.makeopts
menuselect/menuselect --enable cdr_tds menuselect.makeopts

menuselect/menuselect --enable cel_custom menuselect.makeopts
menuselect/menuselect --enable cel_manager menuselect.makeopts
menuselect/menuselect --enable cel_odbc menuselect.makeopts
menuselect/menuselect --enable cel_pgsql menuselect.makeopts
menuselect/menuselect --enable cel_radius menuselect.makeopts
menuselect/menuselect --enable cel_sqlite3_custom menuselect.makeopts
menuselect/menuselect --enable cel_tds menuselect.makeopts

menuselect/menuselect --enable chan_bridge_media menuselect.makeopts
menuselect/menuselect --enable chan_iax2 menuselect.makeopts
menuselect/menuselect --enable chan_pjsip menuselect.makeopts
menuselect/menuselect --enable chan_rtp menuselect.makeopts
menuselect/menuselect --enable chan_alsa menuselect.makeopts
menuselect/menuselect --enable chan_audiosocket menuselect.makeopts
menuselect/menuselect --enable chan_console menuselect.makeopts
menuselect/menuselect --enable chan_mgcp menuselect.makeopts
menuselect/menuselect --enable chan_skinny menuselect.makeopts
menuselect/menuselect --enable chan_unistim menuselect.makeopts
menuselect/menuselect --enable chan_oss menuselect.makeopts
menuselect/menuselect --enable chan_phone menuselect.makeopts
menuselect/menuselect --enable chan_sip menuselect.makeopts

menuselect/menuselect --enable codec_a_mu menuselect.makeopts
menuselect/menuselect --enable codec_adpcm menuselect.makeopts
menuselect/menuselect --enable codec_alaw menuselect.makeopts
menuselect/menuselect --enable codec_codec2 menuselect.makeopts
menuselect/menuselect --enable codec_g722 menuselect.makeopts
menuselect/menuselect --enable codec_g726 menuselect.makeopts
menuselect/menuselect --enable codec_gsm menuselect.makeopts
menuselect/menuselect --enable codec_ilbc menuselect.makeopts
menuselect/menuselect --enable codec_lpc10 menuselect.makeopts
menuselect/menuselect --enable codec_resample menuselect.makeopts
menuselect/menuselect --enable codec_speex menuselect.makeopts
menuselect/menuselect --enable codec_ulaw menuselect.makeopts
menuselect/menuselect --enable codec_opus menuselect.makeopts

menuselect/menuselect --enable format_g719 menuselect.makeopts
menuselect/menuselect --enable format_g723 menuselect.makeopts
menuselect/menuselect --enable format_g726 menuselect.makeopts
menuselect/menuselect --enable format_g729 menuselect.makeopts
menuselect/menuselect --enable format_gsm menuselect.makeopts
menuselect/menuselect --enable format_h263 menuselect.makeopts
menuselect/menuselect --enable format_h264 menuselect.makeopts
menuselect/menuselect --enable format_ilbc menuselect.makeopts
menuselect/menuselect --enable format_ogg_vorbis menuselect.makeopts
menuselect/menuselect --enable format_pcm menuselect.makeopts
menuselect/menuselect --enable format_siren14 menuselect.makeopts
menuselect/menuselect --enable format_siren7 menuselect.makeopts
menuselect/menuselect --enable format_sln menuselect.makeopts
menuselect/menuselect --enable format_wav menuselect.makeopts
menuselect/menuselect --enable format_wav_gsm menuselect.makeopts
menuselect/menuselect --enable format_ogg_speex menuselect.makeopts
menuselect/menuselect --enable format_vox menuselect.makeopts

menuselect/menuselect --enable func_aes menuselect.makeopts
menuselect/menuselect --enable func_base64 menuselect.makeopts
menuselect/menuselect --enable func_blacklist menuselect.makeopts
menuselect/menuselect --enable func_callcompletion menuselect.makeopts
menuselect/menuselect --enable func_callerid menuselect.makeopts
menuselect/menuselect --enable func_cdr menuselect.makeopts
menuselect/menuselect --enable func_channel menuselect.makeopts
menuselect/menuselect --enable func_config menuselect.makeopts
menuselect/menuselect --enable func_curl menuselect.makeopts
menuselect/menuselect --enable func_cut menuselect.makeopts
menuselect/menuselect --enable func_db menuselect.makeopts
menuselect/menuselect --enable func_devstate menuselect.makeopts
menuselect/menuselect --enable func_dialgroup menuselect.makeopts
menuselect/menuselect --enable func_dialplan menuselect.makeopts
menuselect/menuselect --enable func_enum menuselect.makeopts
menuselect/menuselect --enable func_env menuselect.makeopts
menuselect/menuselect --enable func_extstate menuselect.makeopts
menuselect/menuselect --enable func_global menuselect.makeopts
menuselect/menuselect --enable func_groupcount menuselect.makeopts
menuselect/menuselect --enable func_hangupcause menuselect.makeopts
menuselect/menuselect --enable func_holdintercept menuselect.makeopts
menuselect/menuselect --enable func_iconv menuselect.makeopts
menuselect/menuselect --enable func_jitterbuffer menuselect.makeopts             
menuselect/menuselect --enable func_lock menuselect.makeopts
menuselect/menuselect --enable func_logic menuselect.makeopts
menuselect/menuselect --enable func_math menuselect.makeopts
menuselect/menuselect --enable func_md5 menuselect.makeopts
menuselect/menuselect --enable func_module menuselect.makeopts
menuselect/menuselect --enable func_odbc menuselect.makeopts
menuselect/menuselect --enable func_periodic_hook menuselect.makeopts
menuselect/menuselect --enable func_pjsip_aor menuselect.makeopts
menuselect/menuselect --enable func_pjsip_contact menuselect.makeopts
menuselect/menuselect --enable func_pjsip_endpoint menuselect.makeopts
menuselect/menuselect --enable func_presencestate menuselect.makeopts
menuselect/menuselect --enable func_rand menuselect.makeopts
menuselect/menuselect --enable func_realtime menuselect.makeopts
menuselect/menuselect --enable func_sha1 menuselect.makeopts
menuselect/menuselect --enable func_shell menuselect.makeopts
menuselect/menuselect --enable func_sorcery menuselect.makeopts
menuselect/menuselect --enable func_speex menuselect.makeopts
menuselect/menuselect --enable func_sprintf menuselect.makeopts
menuselect/menuselect --enable func_srv menuselect.makeopts
menuselect/menuselect --enable func_strings menuselect.makeopts
menuselect/menuselect --enable func_sysinfo menuselect.makeopts
menuselect/menuselect --enable func_talkdetect menuselect.makeopts
menuselect/menuselect --enable func_timeout menuselect.makeopts
menuselect/menuselect --enable func_uri menuselect.makeopts
menuselect/menuselect --enable func_version menuselect.makeopts
menuselect/menuselect --enable func_vmcount menuselect.makeopts
menuselect/menuselect --enable func_volume menuselect.makeopts
menuselect/menuselect --enable func_evalexten menuselect.makeopts
menuselect/menuselect --enable func_export menuselect.makeopts
menuselect/menuselect --enable func_frame_drop menuselect.makeopts
menuselect/menuselect --enable func_frame_trace menuselect.makeopts
menuselect/menuselect --enable func_json menuselect.makeopts
menuselect/menuselect --enable func_pitchshift menuselect.makeopts
menuselect/menuselect --enable func_sayfiles menuselect.makeopts
menuselect/menuselect --enable func_scramble menuselect.makeopts

menuselect/menuselect --enable pbx_config menuselect.makeopts
menuselect/menuselect --enable pbx_loopback menuselect.makeopts
menuselect/menuselect --enable pbx_spool menuselect.makeopts
menuselect/menuselect --enable pbx_ael menuselect.makeopts
menuselect/menuselect --enable pbx_dundi menuselect.makeopts
menuselect/menuselect --enable pbx_lua menuselect.makeopts
menuselect/menuselect --enable pbx_realtime menuselect.makeopts

menuselect/menuselect --enable res_aeap menuselect.makeopts
menuselect/menuselect --enable res_agi menuselect.makeopts
menuselect/menuselect --enable res_ari menuselect.makeopts
menuselect/menuselect --enable res_ari_applications menuselect.makeopts
menuselect/menuselect --enable res_ari_asterisk menuselect.makeopts
menuselect/menuselect --enable res_ari_bridges menuselect.makeopts
menuselect/menuselect --enable res_ari_channels menuselect.makeopts
menuselect/menuselect --enable res_ari_device_states menuselect.makeopts
menuselect/menuselect --enable res_ari_endpoints menuselect.makeopts
menuselect/menuselect --enable res_ari_events menuselect.makeopts
menuselect/menuselect --enable res_ari_mailboxes menuselect.makeopts
menuselect/menuselect --enable res_ari_model menuselect.makeopts
menuselect/menuselect --enable res_ari_playbacks menuselect.makeopts
menuselect/menuselect --enable res_ari_recordings menuselect.makeopts
menuselect/menuselect --enable res_ari_sounds menuselect.makeopts
menuselect/menuselect --enable res_clialiases menuselect.makeopts
menuselect/menuselect --enable res_clioriginate menuselect.makeopts
menuselect/menuselect --enable res_config_curl menuselect.makeopts
menuselect/menuselect --enable res_config_odbc menuselect.makeopts
menuselect/menuselect --enable res_config_sqlite3 menuselect.makeopts
menuselect/menuselect --enable res_convert menuselect.makeopts
menuselect/menuselect --enable res_crypto menuselect.makeopts
menuselect/menuselect --enable res_curl menuselect.makeopts
menuselect/menuselect --enable res_fax menuselect.makeopts
menuselect/menuselect --enable res_format_attr_celt menuselect.makeopts
menuselect/menuselect --enable res_format_attr_g729 menuselect.makeopts
menuselect/menuselect --enable res_format_attr_h263 menuselect.makeopts
menuselect/menuselect --enable res_format_attr_h264 menuselect.makeopts
menuselect/menuselect --enable res_format_attr_ilbc menuselect.makeopts
menuselect/menuselect --enable res_format_attr_opus menuselect.makeopts
menuselect/menuselect --enable res_format_attr_silk menuselect.makeopts
menuselect/menuselect --enable res_format_attr_siren14 menuselect.makeopts
menuselect/menuselect --enable res_format_attr_siren7 menuselect.makeopts
menuselect/menuselect --enable res_format_attr_vp8 menuselect.makeopts
menuselect/menuselect --enable res_geolocation menuselect.makeopts
menuselect/menuselect --enable res_http_media_cache menuselect.makeopts
menuselect/menuselect --enable res_http_post menuselect.makeopts
menuselect/menuselect --enable res_http_websocket menuselect.makeopts
menuselect/menuselect --enable res_limit menuselect.makeopts
menuselect/menuselect --enable res_manager_devicestate menuselect.makeopts
menuselect/menuselect --enable res_manager_presencestate menuselect.makeopts
menuselect/menuselect --enable res_musiconhold menuselect.makeopts
menuselect/menuselect --enable res_mutestream menuselect.makeopts
menuselect/menuselect --enable res_mwi_devstate menuselect.makeopts
menuselect/menuselect --enable res_odbc menuselect.makeopts
menuselect/menuselect --enable res_odbc_transaction menuselect.makeopts
menuselect/menuselect --enable res_parking menuselect.makeopts
menuselect/menuselect --enable res_pjproject menuselect.makeopts
menuselect/menuselect --enable res_pjsip menuselect.makeopts
menuselect/menuselect --enable res_pjsip_acl menuselect.makeopts
menuselect/menuselect --enable res_pjsip_authenticator_digest menuselect.makeopts
menuselect/menuselect --enable res_pjsip_caller_id menuselect.makeopts
menuselect/menuselect --enable res_pjsip_config_wizard menuselect.makeopts
menuselect/menuselect --enable res_pjsip_dialog_info_body_generator menuselect.makeopts
menuselect/menuselect --enable res_pjsip_diversion menuselect.makeopts
menuselect/menuselect --enable res_pjsip_dlg_options menuselect.makeopts
menuselect/menuselect --enable res_pjsip_dtmf_info menuselect.makeopts
menuselect/menuselect --enable res_pjsip_empty_info menuselect.makeopts
menuselect/menuselect --enable res_pjsip_endpoint_identifier_anonymous menuselect.makeopts
menuselect/menuselect --enable res_pjsip_endpoint_identifier_ip menuselect.makeopts
menuselect/menuselect --enable res_pjsip_endpoint_identifier_user menuselect.makeopts
menuselect/menuselect --enable res_pjsip_exten_state menuselect.makeopts
menuselect/menuselect --enable res_pjsip_geolocation menuselect.makeopts
menuselect/menuselect --enable res_pjsip_header_funcs menuselect.makeopts
menuselect/menuselect --enable res_pjsip_logger menuselect.makeopts
menuselect/menuselect --enable res_pjsip_messaging menuselect.makeopts
menuselect/menuselect --enable res_pjsip_mwi menuselect.makeopts
menuselect/menuselect --enable res_pjsip_mwi_body_generator menuselect.makeopts
menuselect/menuselect --enable res_pjsip_nat menuselect.makeopts
menuselect/menuselect --enable res_pjsip_notify menuselect.makeopts
menuselect/menuselect --enable res_pjsip_one_touch_record_info menuselect.makeopts
menuselect/menuselect --enable res_pjsip_outbound_authenticator_digest menuselect.makeopts
menuselect/menuselect --enable res_pjsip_outbound_publish menuselect.makeopts
menuselect/menuselect --enable res_pjsip_outbound_registration menuselect.makeopts
menuselect/menuselect --enable res_pjsip_path menuselect.makeopts
menuselect/menuselect --enable res_pjsip_pidf_body_generator menuselect.makeopts
menuselect/menuselect --enable res_pjsip_pidf_digium_body_supplement menuselect.makeopts
menuselect/menuselect --enable res_pjsip_pidf_eyebeam_body_supplement menuselect.makeopts
menuselect/menuselect --enable res_pjsip_publish_asterisk menuselect.makeopts
menuselect/menuselect --enable res_pjsip_pubsub menuselect.makeopts
menuselect/menuselect --enable res_pjsip_refer menuselect.makeopts
menuselect/menuselect --enable res_pjsip_registrar menuselect.makeopts
menuselect/menuselect --enable res_pjsip_rfc3326 menuselect.makeopts
menuselect/menuselect --enable res_pjsip_rfc3329 menuselect.makeopts
menuselect/menuselect --enable res_pjsip_sdp_rtp menuselect.makeopts
menuselect/menuselect --enable res_pjsip_send_to_voicemail menuselect.makeopts
menuselect/menuselect --enable res_pjsip_session menuselect.makeopts
menuselect/menuselect --enable res_pjsip_sips_contact menuselect.makeopts
menuselect/menuselect --enable res_pjsip_stir_shaken menuselect.makeopts
menuselect/menuselect --enable res_pjsip_t38 menuselect.makeopts
menuselect/menuselect --enable res_pjsip_transport_websocket menuselect.makeopts
menuselect/menuselect --enable res_pjsip_xpidf_body_generator menuselect.makeopts
menuselect/menuselect --enable res_realtime menuselect.makeopts
menuselect/menuselect --enable res_resolver_unbound menuselect.makeopts
menuselect/menuselect --enable res_rtp_asterisk menuselect.makeopts
menuselect/menuselect --enable res_rtp_multicast menuselect.makeopts
menuselect/menuselect --enable res_security_log menuselect.makeopts
menuselect/menuselect --enable res_sorcery_astdb menuselect.makeopts
menuselect/menuselect --enable res_sorcery_config menuselect.makeopts
menuselect/menuselect --enable res_sorcery_memory menuselect.makeopts
menuselect/menuselect --enable res_sorcery_memory_cache menuselect.makeopts
menuselect/menuselect --enable res_sorcery_realtime menuselect.makeopts
menuselect/menuselect --enable res_speech menuselect.makeopts
menuselect/menuselect --enable res_speech_aeap menuselect.makeopts
menuselect/menuselect --enable res_srtp menuselect.makeopts
menuselect/menuselect --enable res_stasis menuselect.makeopts
menuselect/menuselect --enable res_stasis_answer menuselect.makeopts
menuselect/menuselect --enable res_stasis_device_state menuselect.makeopts
menuselect/menuselect --enable res_stasis_playback menuselect.makeopts
menuselect/menuselect --enable res_stasis_recording menuselect.makeopts
menuselect/menuselect --enable res_stasis_snoop menuselect.makeopts
menuselect/menuselect --enable res_stir_shaken menuselect.makeopts
menuselect/menuselect --enable res_stun_monitor menuselect.makeopts
menuselect/menuselect --enable res_timing_timerfd menuselect.makeopts
menuselect/menuselect --enable res_ael_share menuselect.makeopts
menuselect/menuselect --enable res_audiosocket menuselect.makeopts
menuselect/menuselect --enable res_calendar menuselect.makeopts
menuselect/menuselect --enable res_calendar_caldav menuselect.makeopts
menuselect/menuselect --enable res_calendar_ews menuselect.makeopts
menuselect/menuselect --enable res_calendar_icalendar menuselect.makeopts
menuselect/menuselect --enable res_config_ldap menuselect.makeopts
menuselect/menuselect --enable res_config_pgsql menuselect.makeopts
menuselect/menuselect --enable res_fax_spandsp menuselect.makeopts
menuselect/menuselect --enable res_hep menuselect.makeopts
menuselect/menuselect --enable res_hep_pjsip menuselect.makeopts
menuselect/menuselect --enable res_hep_rtcp menuselect.makeopts
menuselect/menuselect --enable res_phoneprov menuselect.makeopts
menuselect/menuselect --enable res_pjsip_aoc menuselect.makeopts
menuselect/menuselect --enable res_pjsip_history menuselect.makeopts
menuselect/menuselect --enable res_pjsip_phoneprov_provider menuselect.makeopts
menuselect/menuselect --enable res_prometheus menuselect.makeopts
menuselect/menuselect --enable res_smdi menuselect.makeopts
menuselect/menuselect --enable res_snmp menuselect.makeopts
menuselect/menuselect --enable res_statsd menuselect.makeopts
menuselect/menuselect --enable res_timing_pthread menuselect.makeopts
menuselect/menuselect --enable res_tonedetect menuselect.makeopts
menuselect/menuselect --enable res_adsi menuselect.makeopts
menuselect/menuselect --enable res_monitor menuselect.makeopts

menuselect/menuselect --enable OPTIONAL_API menuselect.makeopts

menuselect/menuselect --enable astcanary menuselect.makeopts
menuselect/menuselect --enable astdb2sqlite3 menuselect.makeopts
menuselect/menuselect --enable astdb2bdb menuselect.makeopts
menuselect/menuselect --enable muted menuselect.makeopts

menuselect/menuselect --enable CORE-SOUNDS-EN-WAV menuselect.makeopts
menuselect/menuselect --enable CORE-SOUNDS-EN-GSM menuselect.makeopts

menuselect/menuselect --enable MOH-OPSOUND-WAV menuselect.makeopts
menuselect/menuselect --enable MOH-OPSOUND-GSM menuselect.makeopts

menuselect/menuselect --enable EXTRA-SOUNDS-EN-WAV menuselect.makeopts
